---
title: "June 2018 post-matlab"
output: html_notebook
---

# Post matlab stuff

```{r}
source("LoadLibs.R")
source("LoadProcessZ1New.R")
attach(knew.molten)

# Merge more details
freeze_details = read.csv("freeze_details.csv")
group_details = read.csv("group_details.csv", header=T, encoding = "UTF-8-BOM")
names(group_details)[1] = "GROUP"

knew.molten2 = merge(knew.molten, freeze_details, by="ID")
knew.molten2 = merge(knew.molten2, group_details, by="GROUP")


```






# Calculate the weighted counts for whole brain
## Point-range graphs
```{r}

# density, weight by ROI area, EACH BRIGHTNESS
for (bright in c('low', 'mid', 'hi', 'total')) {
  print(
    knew.molten2 %>%
      filter(UNITS == "density") %>%
      filter(BRIGHTNESS == bright) %>%
      group_by(ID, GROUP, EXPT, CHANNEL, variable) %>%
      summarize(weighted = weighted.mean(value, ROIAreapx)) %>%
      ggplot() + aes(GROUP, weighted, color=EXPT) + 
      stat_summary(fun.y = "mean", geom="point") + 
      stat_summary(fun.data = "mean_se", geom="linerange") + 
      facet_wrap(~CHANNEL, scales="free") + 
      ggtitle(paste(c("Whole brain, weighted, density"),bright,"cells"))
  )
}

# counts normalized, weight by ROI area, EACH BRIGHTNESS
for (bright in c('low', 'mid', 'hi', 'total')) {
  print(
    knew.molten2 %>%
      filter(UNITS == "counts") %>%
      filter(NORMD == 'yes') %>%
      filter(BRIGHTNESS == bright) %>%
      group_by(ID, GROUP, EXPT, CHANNEL, variable) %>%
      summarize(weighted = weighted.mean(value, ROIAreapx)) %>%
      ggplot() + aes(GROUP, weighted, color=EXPT) + 
      stat_summary(fun.y = "mean", geom="point") + 
      stat_summary(fun.data = "mean_se", geom="linerange") + 
      facet_wrap(~CHANNEL, scales="free") + 
      ggtitle(paste(c("Whole brain, weighted, counts"),bright,"cells"))
  )
}


```

## Heatmaps
```{r}

knew.molten2 %>%
  ddply(.(EXPT, GROUP, CHANNEL), transform, z = scale(value)) %>%
  ggplot() + aes(GROUP, EXPT, z=z, fill=z) +
  geom_tile() + scale_fill_gradient2(low='dark blue', mid='white', high='red') +
  facet_wrap(~CHANNEL)
  

```


# Calculate weighted means for each system

```{r, fig.width=9.5, fig.height=5}

# systems, weighted by ROI area
for (bright in c('low', 'mid', 'hi', 'total')) {
  print(
    knew.molten2 %>%
      filter(UNITS == "density") %>%
      filter(BRIGHTNESS == bright) %>%
      group_by(ID, System, GROUP, EXPT, CHANNEL, variable) %>%
      summarize(weighted = weighted.mean(value, ROIAreapx)) %>%
      ggplot() + aes(GROUP, weighted, color=EXPT) + 
      stat_summary(fun.y = "mean", geom="point") + 
      stat_summary(fun.data = "mean_se", geom="linerange") + 
      facet_wrap(CHANNEL~System, scales="free", ncol=16) + 
      ggtitle(paste(c("Whole brain, weighted, counts"),bright,"cells"))
  )
}

# make heatmap
systems.scaled = systems %>%
  ddply(.(ID, CHANNEL, System), 
        transform, z = (scale(value)))


```


