---
title: "R Notebook"
output: html_notebook
---

# Make Confusion Matrix for GFP from LDA data

```{r}

initial_groups = function (x) {
  y = case_when(x == 'AGED SHOCK' ~ "AS",
                x == 'AGED CONTEXT' ~ "AC",
                x == 'YOUNG SHOCK' ~ 'YS',
                x == 'YOUNG CONTEXT' ~ 'YC')
  return(y)
}

get_predict_table = function(df, dfname) {
  data.for.lda = df %>%
    ddply(.(ID), transform, z = scale(weighted)) %>%
    dcast(ID ~ System, value.var="z", fun.aggregate = mean) 
  
  data.for.lda = merge(data.for.lda, animal_details %>% aged() %>%
                         mutate(GRAIN = paste(EXPT, VALENCE)) %>% dplyr::select(ID, GRAIN), by="ID")
  
  # remove spaces? 
  names(data.for.lda) = gsub(" ", "_", names(data.for.lda))
  names(data.for.lda) = gsub("-", ".", names(data.for.lda))
  
  # impute missing data
  data.for.lda = mice::complete(mice(data.for.lda, m=5, seed=25))
  
  # lda
  r <- lda(formula = GRAIN ~ ., 
           data = data.for.lda[,2:ncol(data.for.lda)], 
           prior = c(1,1,1,1)/4)
    
  prop = r$svd^2/sum(r$svd^2)
  
  plda = predict(object = r, # predictions
                 newdata = data.for.lda)
  print(plda$class)
  predict.table = table(plda$class, data.for.lda$GRAIN)
  
  rownames(predict.table) = sapply(rownames(predict.table), initial_groups)
  colnames(predict.table) = sapply(colnames(predict.table), initial_groups)
  return(predict.table)
  # row is actual
  # col is predicted
}

```

```{r, fig.width=2.25, fig.height=1.5}

predict.gfp = get_predict_table(gfp, "GFP")
predict.gfp = prop.table(predict.gfp, 1)

ggplot(melt(predict.gfp)) + aes(Var1, Var2, fill=value) + geom_tile() +
  scale_fill_gradient2(low="black", high="dark green", limits=c(0,1)) +
  xlab("Actual") + ylab("Predicted") + labs(fill="accuracy") +
  theme_light() +
  theme(axis.text = element_text(size=14),
        axis.title = element_text(size=18),
        legend.text = element_text(size=12),
        legend.title = element_text(size=14)) 

```


```{r, fig.width=2.25, fig.height=1.5}

predict.arc = get_predict_table(arc, "ArcIHC")
predict.arc = prop.table(predict.arc, 1)

ggplot(melt(predict.arc)) + aes(Var1, Var2, fill=value) + geom_tile() +
  scale_fill_gradient2(low="white", high="purple") +
  xlab("Actual") + ylab("Predicted") + labs(fill="accuracy") +
  theme_light() +
  theme(axis.text = element_text(size=14),
        axis.title = element_text(size=18),
        legend.text = element_text(size=12),
        legend.title = element_text(size=14)) 

```

```{r, fig.width=1.5, fig.height=1}

predict.nol = get_predict_table(nol, "NormOL")
predict.nol = prop.table(predict.nol, 1)

ggplot(melt(predict.nol)) + aes(Var1, Var2, fill=value) + geom_tile() +
  scale_fill_gradient2(low="black", high="gold", limits=c(0,1)) +
  xlab("Actual") + ylab("Predicted") + labs(fill="accuracy") +
  theme_light()

```
